-- Schema before Drizzle and activity history; generated by the previous migration paths.

    CREATE TABLE IF NOT EXISTS office_whiteboards (id text PRIMARY KEY, elements jsonb NOT NULL DEFAULT '[]'::jsonb, updated_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS office_settings (id integer PRIMARY KEY CHECK(id = 1), password boolean NOT NULL DEFAULT true, sso boolean NOT NULL DEFAULT false, version integer NOT NULL DEFAULT 1);
    INSERT INTO office_settings (id) VALUES (1) ON CONFLICT DO NOTHING;
    CREATE TABLE IF NOT EXISTS office_audit (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, actor text NOT NULL, action text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS workspace_settings (id integer PRIMARY KEY CHECK(id = 1), name text NOT NULL DEFAULT 'Team workspace', map_id text NOT NULL DEFAULT 'nature-small', revision integer NOT NULL DEFAULT 1);
    ALTER TABLE workspace_settings ADD COLUMN IF NOT EXISTS features jsonb NOT NULL DEFAULT '{"whiteboard":true}'::jsonb;
    CREATE TABLE IF NOT EXISTS office_files (id text PRIMARY KEY, board_id text NOT NULL, object_key text UNIQUE NOT NULL, name text NOT NULL, size integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
    ALTER TABLE office_files ADD COLUMN IF NOT EXISTS created_by text NOT NULL DEFAULT '';
    INSERT INTO workspace_settings (id) VALUES (1) ON CONFLICT DO NOTHING;
  
create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null, "username" text unique, "displayUsername" text, "role" text not null, "approved" boolean not null, "avatar" text not null, "availability" text not null, "statusText" text not null, "mustChangePassword" boolean not null);

create table "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade, "method" text not null, "policyVersion" integer not null);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");